"""empty message

Revision ID: f742f029de07
Revises: bfc7876e5c05
Create Date: 2020-09-06 17:03:36.447223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f742f029de07'
down_revision = 'bfc7876e5c05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('doctoruser', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'user', ['doctoruser'], ['username'])
    op.drop_column('users', 'u_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('u_name', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'user', ['u_name'], ['username'])
    op.drop_column('users', 'doctoruser')
    # ### end Alembic commands ###
